# .github/workflows/update_posts.yml
name: Update Posts Index

on:
  push:
    paths:
      - 'posts/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate posts.json
        run: |
          echo "[" > posts.json
          ls posts/*.md | while read file; do
            slug=$(basename "$file" .md)
            echo "  {\"slug\": \"$slug\"}," >> posts.json
          done
          echo "]" >> posts.json
          # Remove trailing comma
          sed -i '$ s/,$//' posts.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git commit -m "Update posts index" || exit 0
          git push
          
