# .github/workflows/update_posts.yml
name: Update Posts Index

on:
  push:
    paths:
      - 'posts/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate posts.json
        run: |
          # Create proper JSON array
          echo "Generating posts.json..."
          files=$(ls posts/*.md | sed 's/posts\///g' | sed 's/\.md//g')
          echo "[" > posts.json
          first=true
          for slug in $files; do
            if [ "$first" = false ]; then
              echo "," >> posts.json
            fi
            echo "  {\"slug\": \"$slug\"}" >> posts.json
            first=false
          done
          echo "]" >> posts.json
          echo "Generated posts.json:"
          cat posts.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update posts index"
          git push
