name: Update Posts Index

on:
  push:
    paths:
      - 'posts/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate valid posts.json
        run: |
          # Install jq for JSON processing
          sudo apt-get install jq
          
          # Get list of markdown files and convert to JSON array
          find posts -name "*.md" -exec basename {} .md \; | \
            jq -R . | \
            jq -s '{posts: [.[] | {slug: .}]}' | \
            jq '.posts' > posts.json
          
          # Verify the JSON
          jq empty posts.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update posts index"
          git push
          